version: '3.6'

services:
  postgres:  # Renamed from `postgres` to `keycloakdb` if you prefer the name `keycloakdb`
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak_web:
    image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: P@dmini2
      
    command: start-dev
    depends_on:
      - postgres  # Corrected to match the actual service name
    ports:
      - 8090:8080
      

volumes:
  postgres_data:
